package Forms;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

public class Passwords_editing extends javax.swing.JFrame {
    /** Creates new form Passwords_editing */
    int admins = 0;
    public Passwords_editing() {
        initComponents();
        selectData();
    }
    
    Connection con = null;
    ResultSet Rs = null;
    Statement st = null;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();

        setTitle("Passwords");
        setLocation(new java.awt.Point(300, 200));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Password", "Admin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setRowHeight(25);
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jTable2MouseDragged(evt);
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable2MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(30);
        }

        jButton1.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jButton1.setText("Add");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jButton2.setText("Update");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jButton3.setText("Remove");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCheckBox1.setText("Admin");

        jButton4.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jButton4.setText("Exit");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBox1))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void selectData(){
        try{
            String dir = System.getProperty("user.dir");
            con = DriverManager.getConnection("jdbc:derby:"+ dir +"/Project", "Abdallah", "1234");
            st = con.createStatement();
            Rs = st.executeQuery("Select * from ABDALLAH.LOGIN_INFO");
            jTable1.setModel(DbUtils.resultSetToTableModel(Rs));
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    public void insertData(){
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        model.setRowCount(0);
        for (int i = 0; i < jTable1.getRowCount() ; i++){
            Object[] row = {jTable1.getModel().getValueAt(i, 0), jTable1.getModel().getValueAt(i, 1), jTable1.getModel().getValueAt(i, 2)};
            model.addRow(row);
        }
        if (jTable2.getRowCount() != 0)
            jTable2.setRowSelectionInterval(0, 0);
    }
    public void putData(){
        if (jTable2.getRowCount() == 0)
            return;
        jTextField1.setText(jTable2.getModel().getValueAt(jTable2.getSelectedRow(), 0).toString());
        jTextField2.setText(jTable2.getModel().getValueAt(jTable2.getSelectedRow(), 1).toString());
        jCheckBox1.setSelected((boolean)jTable2.getModel().getValueAt(jTable2.getSelectedRow(), 2));
    }
    public boolean isDublicate(int skip){
        for (int i = 0; i < jTable2.getRowCount(); i++){
            if (skip == i)
                continue;
                if (jTable2.getModel().getValueAt(i, 0).toString().equals(jTextField1.getText().toString().trim())){
                        JOptionPane.showMessageDialog(this, "Username is dublicated", "Message", JOptionPane.ERROR_MESSAGE);
                        return true;
                }
            }
        return false;
    }
    public void setAdminCount(){
        admins = 0;
        for (int i = 0; i < jTable2.getRowCount(); i++)
            if ((boolean)jTable2.getModel().getValueAt(i, 2)) admins++;
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // When this form opened
        jPanel1.setVisible(false);
        insertData();
        putData();
        jTable2.setSelectionBackground(new Color(0,120,215));
        for (int i = 0; i < jTable2.getRowCount(); i++)
            if ((boolean)jTable2.getModel().getValueAt(i, 2)) admins++;
    }//GEN-LAST:event_formWindowOpened

    private void jTable2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MousePressed
        putData();
    }//GEN-LAST:event_jTable2MousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // Add
        if (jTextField1.getText().equals("") || jTextField2.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Enter all data", "Message", JOptionPane.WARNING_MESSAGE);
            putData();
            return;
        }
        if (isDublicate(-1))
            return;
        try{
            String dir = System.getProperty("user.dir");
            con = DriverManager.getConnection("jdbc:derby:"+ dir +"/Project", "Abdallah", "1234");
            PreparedStatement add = con.prepareStatement("insert into LOGIN_INFO values(?,?,?)");
            add.setString(1, jTextField1.getText());
            add.setString(2, jTextField2.getText());
            add.setBoolean(3, jCheckBox1.isSelected());
            int row = add.executeUpdate();
            selectData();
            insertData();
            jTable2.setRowSelectionInterval(0, jTable2.getRowCount() - 1);
            setAdminCount();
            JOptionPane.showMessageDialog(this, "Added successfully");
            con.close();
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // Update
        if (jTable2.getRowCount() == 0)
            return;
        if (jTextField1.getText().equals("") || jTextField2.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Enter all data", "Message", JOptionPane.WARNING_MESSAGE);
            putData();
            return;
        }
        TableModel table = jTable2.getModel();
        int selectedRow = jTable2.getSelectedRow();
        if ((table.getValueAt(selectedRow, 0).toString().equals(jTextField1.getText().toString().trim()) && table.getValueAt(selectedRow, 1).equals(jTextField2.getText()) &&
                table.getValueAt(selectedRow, 2).equals(jCheckBox1.getModel().isSelected())) || isDublicate(selectedRow))
            return;
        
        if (admins == 1 && (boolean)jTable2.getModel().getValueAt(jTable2.getSelectedRow(), 2) &&
                !jCheckBox1.getModel().isSelected()){
            int response = JOptionPane.showConfirmDialog(this, "No admin will exist, any one can log in as admin, Continue updating?", "warning", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (response != 0){
                putData();
                return;
            }
        }else{
            int response = JOptionPane.showConfirmDialog(this, "Continue updating?", "Message", JOptionPane.YES_NO_OPTION);
            if (response != 0)
                return;
        }
        
        try{
            String dir = System.getProperty("user.dir");
            con = DriverManager.getConnection("jdbc:derby:"+ dir +"/Project", "Abdallah", "1234");
            PreparedStatement update = con.prepareStatement("update LOGIN_INFO set Name = '"+ jTextField1.getText().toString().trim() +"', Password = '"+ jTextField2.getText() +"', Admin = '"+ jCheckBox1.getModel().isSelected() +"'where Name = '"+ jTable2.getModel().getValueAt(jTable2.getSelectedRow(), 0) +"'");
            int row = update.executeUpdate();
            selectData();
            insertData();
            jTable2.setRowSelectionInterval(0, selectedRow);
            setAdminCount();
            JOptionPane.showMessageDialog(this, "Updated successfully");
            con.close();
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        // Remove
        if (jTable2.getRowCount() == 0)
            return;
        if (admins == 1 && (boolean)jTable2.getModel().getValueAt(jTable2.getSelectedRow(), 2)){
            int response = JOptionPane.showConfirmDialog(this, "No admin will exist, any one can log in as admin, Continue removing?", "warning", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (response != 0){
                putData();
                return;
            }
        }else{
            int response = JOptionPane.showConfirmDialog(this, "Continue removing?", "Message", JOptionPane.YES_NO_OPTION);
            if (response != 0)
                return;
        }
        
        TableModel table = jTable2.getModel();
        int selectedRow = jTable2.getSelectedRow();
        try{
            String dir = System.getProperty("user.dir");
            con = DriverManager.getConnection("jdbc:derby:"+ dir +"/Project", "Abdallah", "1234");
            PreparedStatement remove = con.prepareStatement("delete from LOGIN_INFO where Name = '"+ jTable2.getModel().getValueAt(jTable2.getSelectedRow(), 0) +"'");
            int row = remove.executeUpdate();
            selectData();
            insertData();
            putData();
            setAdminCount();
            JOptionPane.showMessageDialog(this, "Removed successfully");
            con.close();
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3MousePressed

    private void jTable2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseDragged
        putData();
    }//GEN-LAST:event_jTable2MouseDragged

    private void jButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MousePressed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton4MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Passwords_editing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Passwords_editing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Passwords_editing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Passwords_editing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {}
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
